spring:
  application:
    name: notification-service

  profiles:
    active: dev

  # H2 Database Configuration
  datasource:
    url: jdbc:h2:mem:notificationdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  # H2 Console Configuration
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false
        trace: false

  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none  # Disable Hibernate auto DDL
    show-sql: true
    defer-datasource-initialization: true  # Ensure schema.sql runs before data.sql
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 25
        order_inserts: true
        order_updates: true

  # SQL Initialization
  sql:
    init:
      mode: always  # Always run schema.sql
      platform: h2  # Explicitly set the platform
      continue-on-error: false  # Fail on SQL errors

# Server Configuration
server:
  port: 9000
  servlet:
    context-path: /

# Logging Configuration
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web: INFO

info:
  app:
    name: notification-service
    description: Notification Service Microservice
    version: 1.0.0